config/routes.rb
InitialRelease::Application.routes.draw do

  resources :works

  mount Ckeditor::Engine => '/ckeditor'

	match 'admin' => "authentication#index"
  match 'login' => "authentication#login"
  match 'logout' => "authentication#logout"

	match 'construction' => "pages#show", :as => 'construction', :hiperlink => 'etap'
	match 'add_image' => "projects#add_image", :as => 'add_image_proj'
	match 'del_image' => "projects#del_image", :as => 'del_image_proj'
	match 'main_image' => "projects#main_image", :as => 'main_image_proj'

	resources :pages
	resources :projects do
		resources :house_prices
	end

  match ':hiperlink' => "pages#show", :as => 'hiperlink'

	root :to => "pages#show", :hiperlink => 'main'

end

app/models/work.rb
class Work < ActiveRecord::Base
	has_attached_file :real, :styles => {
  	:thumb=> ["180x120", :jpg], :small  => ["300>x300", :jpg], :normal => ["600x600>", :jpg]
  }
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
	before_filter :authorize, :except => [:show, :index]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @work = Work.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/new
  # GET /works/new.json
  def new
    @work = Work.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/1/edit
  def edit
    @work = Work.find(params[:id])
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(params[:work])

    respond_to do |format|
      if @work.save
        format.html { redirect_to works_url, notice: 'Work was successfully created.' }
        format.json { render json: @work, status: :created, location: @work }
      else
        format.html { render action: "new" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /works/1
  # PUT /works/1.json
  def update
    @work = Work.find(params[:id])

    respond_to do |format|
      if @work.update_attributes(params[:work])
        format.html { redirect_to works_url, notice: 'Work was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work = Work.find(params[:id])
    @work.destroy

    respond_to do |format|
      format.html { redirect_to works_url }
      format.json { head :ok }
    end
  end
end

app/views/works/_form.html.erb
<%= form_for(@work, :multipart => true) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_area :info %>
  </div>
  <div class="field">
    <%= f.label :real %><br />
    <%= f.file_field :real %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.haml
%h1 Наши работы: жилые и дачные деревянные дома, бани
- if admin?
	= link_to 'New work', new_work_path if admin?
	%br/
- @works.each do |work|
	- if admin?
		= link_to(edit_work_path(work), :class=>'rowbottom-work') do
			= image_tag work.real.url(:thumb), :class => 'proj-img'
			.proj-name= work.info
			.clear
	-else
		= link_to(work.real.url, :class=>'rowbottom-work', :target=>'blank', :title=>"#{work.info}") do
			= image_tag work.real.url(:thumb), :class => 'proj-img', :alt=>"Деревянный дом: #{work.info}"
			.proj-name= work.info
			.clear

app/views/works/new.html.erb
<h1>New work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @work.name %>
</p>

<p>
  <b>Info:</b>
  <%= @work.info %>
</p>


<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>