config/routes.rb
InitialRelease::Application.routes.draw do

  resources :works

  mount Ckeditor::Engine => '/ckeditor'

	match 'admin' => "authentication#index"
  match 'login' => "authentication#login"
  match 'logout' => "authentication#logout"

	match 'construction' => "pages#show", :as => 'construction', :hiperlink => 'etap'
	match 'add_image' => "projects#add_image", :as => 'add_image_proj'
	match 'del_image' => "projects#del_image", :as => 'del_image_proj'
	match 'main_image' => "projects#main_image", :as => 'main_image_proj'

	resources :pages
	resources :projects do
		resources :house_prices
	end

  match ':hiperlink' => "pages#show", :as => 'hiperlink'

	root :to => "pages#show", :hiperlink => 'main'

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= f.label "Visible in list" %><%= f.check_box :visible %>
  </div>
    <div class="field">
      <%= f.label :head %><br />
      <%= f.text_field :head, :style=>"width:785px" %>
    </div>
    <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :style=>"width:785px" %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :style=>"width:785px" %>
  </div>
  <div class="field">
    <%= f.label :hiperlink %><br />
    <%= f.text_field :hiperlink, :style=>"width:785px" %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= cktext_area_tag("page[body]", @page.body, :input_html => {:cols => 10, :rows => 20}, :toolbar => 'MyToolbar') %>
  </div>
  <br />
  <div class="actions" style="text-align:right">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.haml
%ul
	- @pages.each do |page|
		%li
			= link_to page.title, hiperlink_path(page.hiperlink)
			= link_to 'Edit', edit_page_path(page) if admin?
			= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete if admin?
= link_to 'New Page', new_page_path if admin?

app/views/pages/main.html.erb
    <h1>ГЛАВНАЯ</h1>
    <p><%= image_tag "images/photo3.jpg", :width=>"167", :height=>"127" %>Наша фирма занимается 
    <%= link_to Page.find_by_name('price') do %><%= "производством и продажей " %><strong>оцилиндрованного бревна</strong><% end %> Ø от 16 до 22 см, пиломатериалов (брус, доска, <strong>столярная доска</strong>), строительством коттеджей, домов и бань из оцилиндрованного бревна по Вашим и своим проектам, включая монтаж инженерных сетей.  </p>
    <p> Мы уделяем большое внимание качеству древесины и используем только экологически чистый материал. В последнее время деревянные дома из оцилиндрованного бревна становятся все более популярными во всем мире, ведь древесина - это уникальнейший материал, созданный самой Природой, обладающий целым рядом положительных качеств, выгодно отличающих ее от других строительных материалов. А современный дизайн деревянных домов из оцилиндрованного бревна позволяет строить жилье, отвечающее всем требованиям о комфорте даже самых требовательных Заказчиков. </p>
    <p> Стремясь сделать работу с нами как можно более удобной и комфортной для заказчика, мы берем на себя максимум забот по организации строительства, обеспечивая выполнение всех базовых и сопутствующих работ. </p>
    <div class="morebutton1"> <%= link_to "ДАЛЕЕ", construction_path %></div>
  </div>
  <div id="boxleft">
    <div class="box_left"></div>
    <div class="box_middle">
      <h2>ПРОЕКТЫ</h2>
      <p><%= image_tag "images/proj.png", :width=>"82", :height=>"82" %> Перед началом любого строительства необходимо определиться с проектом будущего дома. Важно подобрать проект дома из оцилиндрованного бревна, который не только нравился бы внешне, но и подходил Вам функционально, а также обязательно был технологически выверен, надёжен и практичен в эксплуатации.  </p>
<div class="morebutton2"><%= link_to "ДАЛЕЕ", projects_path %></div>
    </div>
    <div class="box_right"></div>
  </div>
  <div id="boxright">
    <div class="box_left"></div>
    <div class="box_middle">
      <h2>ЦЕНЫ</h2>
      <p><%= image_tag "images/photo2.jpg", :width=>"90", :height=>"83" %>В общем случае, на стоимость строительства деревянного дома из оцилиндрованного бревна влияет: вид и размеры фундамента; материал стен (диаметр бревна, вид древесины); оптимальность размеров конструкции; высота этажей; сложность строительной системы дома; сложность и материал кровли; удаленность строительства.  .</p>
      <div class="morebutton2"><%= link_to "ДАЛЕЕ", Page.find_by_name('price') %></div>
    </div>
    <div class="box_right"></div>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.haml
%h1= @page.title
%p!= @page.body
= link_to 'Edit', edit_page_path(@page) if admin?
= link_to 'Back', pages_path if admin?