config/routes.rb
InitialRelease::Application.routes.draw do

  resources :works

  mount Ckeditor::Engine => '/ckeditor'

	match 'admin' => "authentication#index"
  match 'login' => "authentication#login"
  match 'logout' => "authentication#logout"

	match 'construction' => "pages#show", :as => 'construction', :hiperlink => 'etap'
	match 'add_image' => "projects#add_image", :as => 'add_image_proj'
	match 'del_image' => "projects#del_image", :as => 'del_image_proj'
	match 'main_image' => "projects#main_image", :as => 'main_image_proj'

	resources :pages
	resources :projects do
		resources :house_prices
	end

  match ':hiperlink' => "pages#show", :as => 'hiperlink'

	root :to => "pages#show", :hiperlink => 'main'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :images, :dependent => :destroy
	has_many :house_prices, :dependent => :destroy

	def sizes
		s = []
		house_prices.each do |pr|
			s << pr.size
		end
		s
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authorize, :except => [:show, :index]

  def add_image
  	@project = Project.find(params[:project_id])
  	if params[:photos]
      params[:photos].each do |p|
        image = Image.new(:photo=>p)
        @project.images << image
			end
			@project.save
		end
  	#redirect_to @project
  	render :partial => 'imagelist'
  end

  def del_image
  	@project = Project.find(params[:proj_id])
  	Image.find(params[:image_id]).destroy
		render 'edit'
  end

  def main_image
  	@project = Project.find(params[:proj_id])
  	Image.find(params[:image_id]).set_main
  	render 'edit'
  end

  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to edit_project_path(@project), notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to edit_project_path(@project), notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for(@project) do |f|
	.field
		= f.label :name
		%br/
		= f.text_field :name, :style=>"width:795px"
	.field{:style=>'float:left;'}
		= f.label :info
		%br/
		= f.text_area :info
	.field{:style=>'float:right;'}
		= f.label :body
		%br/
		= cktext_area_tag("project[body]", @project.body, :width=> 400, :toolbar => 'MyToolbar')# f.text_area :body
	.clear
	-#.field{:style=>'float:left;'}
	-#	= f.label :price
	-#	%br/
	-#	= f.number_field :price
	-#.field{:style=>'float:left;'}
	-#	= f.label :area
	-#	%br/
	-#	= f.number_field :area
	.actions{:style=>'float:right;'}
		%br/
		= f.submit
	.clear
%hr/
%table{:width=>'100%'}
	%tr
		%th{:colspan=>5} Стоимость проекта
	- @project.house_prices.each do |price|
		%tr
			%td{:width=>100,:style=>"border-bottom:solid 1px grey;"} Диаметр бревна
			%td{:width=>30,:style=>"text-align:center;border-bottom:solid 1px grey;"}= price.size
			%td{:width=>100,:style=>"border-bottom:solid 1px grey;"} Стоимость проекта
			%td{:width=>30,:style=>"text-align:center;border-bottom:solid 1px grey;"}= price.count
			%td{:width=>30}
				= link_to([@project, price], method: :delete) do
					= image_tag "images/del.png"
%br/

app/views/projects/_imagelist.html.haml
- @project.images.each do |image|
	= image_tag image.photo.url(:thumb)
	= link_to main_image_proj_path(:proj_id=>@project.id, :image_id=>image.id) do
		= image_tag(image.main == true ? 'images/favorite.png' : 'images/nonfavorite.png', :style=>"margin-left:-70px;margin-top:8px;")
	= link_to del_image_proj_path(:proj_id=>@project.id, :image_id=>image.id) do
		= image_tag 'images/del.png', :style=>"margin-left:-40px;margin-top:8px;"
.clear
%br/

app/views/projects/edit.html.haml
%h1 Редактирование проекта
= render 'form'
= form_for([@project, HousePrice.new]) do |f|
	= f.label 'диаметр бревна:'
	= f.number_field :size
	= f.label 'стоимость проекта:'
	= f.text_field :count
	= f.submit 'добавить стоимость', :style => 'float:right'
	.clear
%hr/
%br/
#divtoupdate
	= render 'imagelist'
= form_tag(add_image_proj_path, :multipart => true, :id => 'myForm' ) do
	= hidden_field_tag :project_id, @project.id
	%input{:type=>'file', :name=>'photos[]'}
	%br/
	= submit_tag 'добавить файл'
= link_to 'Show', @project
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Проекты деревянных домов из оцилиндрованного бревна
- if admin?
	= link_to 'New Project', new_project_path if admin?
	%br/
- @projects.each do |pr|
	.proj-list
		= link_to(project_path(pr)) do
			= image_tag Image.favorite(pr.id).photo.url(:thumb), :class => 'proj-img' if pr.images != [] && Image.favorite(pr.id)
		- if pr.house_prices != []
			%select.select-price
				- pr.house_prices.each do |price|
					%option{:value=>number_to_currency(price.count*8000, :unit=>'руб', :precision=>0, :format=>"%n %u", :delimiter => " ")}= "Диаметр бревна " + price.size.to_s + " мм"
		.proj-name
			= link_to truncate(pr.name, :length=>20, :ommission=>'...'), project_path(pr)
		.proj-info!= pr.info.gsub("\r\n", "<br />")
		- if pr.house_prices != []
			.proj-price= number_to_currency(pr.house_prices.first.count*8000, :unit=>'руб', :precision=>0, :format=>"%n %u", :delimiter => " ")
		.clear

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.haml
=# javascript_include_tag "/javascripts/jquery.tinyTips.js", "/javascripts/jqgalscroll.js"
=# stylesheet_link_tag    "jqGalScroll.css", "tinyTips.css"
%h1= @project.name
= link_to 'Edit', edit_project_path(@project) if admin?
= link_to 'Back', projects_path if admin?
.img-list{:style=>"float:left; width:320px;"}
	- count = 1
	- @project.images.each do |image|
		= link_to image.photo.url, :target=>"_blank", :title=>"деревянные дома: #{@project.name} (рис. #{count})" do
			= image_tag image.photo.url(:small), :style=>"margin:10px auto;", :alt=>"деревянные дома: #{@project.name}"
		- count+=1
.boxright
	.box_left
	.box_middle{:style=>'width:420px; height:1300px;'}
		%p{:style=>'font-weight:bold;font-size:15px;padding-top:20px;padding-left:20px;'}!= @project.info.gsub("\r\n", "<br />")
		%br/
		%p
			Для данного проекта требуется:
			%br/
			- @project.house_prices.each do |price|
				%nobr
					= price.count
					куб.м. оцилиндрованного бревна Ø
					= price.size
					&nbsp;мм;&nbsp;
				%br/
			%br/
			!= @project.body
		.morebutton3{:style=>'height:25px'}
			= link_to 'вернуться к списку проектов', projects_path
	.box_right
.clear
%br/