config/routes.rb
InitialRelease::Application.routes.draw do

  resources :works

  mount Ckeditor::Engine => '/ckeditor'

	match 'admin' => "authentication#index"
  match 'login' => "authentication#login"
  match 'logout' => "authentication#logout"

	match 'construction' => "pages#show", :as => 'construction', :hiperlink => 'etap'
	match 'add_image' => "projects#add_image", :as => 'add_image_proj'
	match 'del_image' => "projects#del_image", :as => 'del_image_proj'
	match 'main_image' => "projects#main_image", :as => 'main_image_proj'

	resources :pages
	resources :projects do
		resources :house_prices
	end

  match ':hiperlink' => "pages#show", :as => 'hiperlink'

	root :to => "pages#show", :hiperlink => 'main'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  <%- if controller_name=='projects' %>
    <%= 'Деревянные дома: проекты домов из оцилиндрованного бревна' %>
  <%- elsif controller_name=='works' %>
    <%= 'Деревянные дома: построенные дома "Воронеж лес"' %>
  <%- elsif controller_name=='pages' and @page %>
    <%= @page.head %>
  <%- elsif controller_name=='pages' and @page==nil %>
    <%= 'Воронеж лес: статьи' %>
  <% end %>
  </title>
  <%= favicon_link_tag 'images/logo.png' %>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    params[:controller] %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] %>
  <%= javascript_include_tag "/javascripts/ckeditor/ckeditor.js" if admin? %>
  <%= javascript_include_tag "/javascripts/jquery.form.js" if admin? %>
  <%= javascript_include_tag "/javascripts/photo.js" if admin? %>
  <%= csrf_meta_tags %>
  <meta name="robots" content="all">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <%- if controller_name=='projects' %>
    <meta name="keywords" content="Деревянные дома бани проекты оцилиндрованное бревно Воронеж" />
    <meta name="description" content="Проекты деревянных домов и бань из оцилиндрованного бревна в Воронеже" />
  <%- elsif controller_name=='works' %>
    <meta name="keywords" content="Деревянные дома бани готовые оцилиндрованное бревно Воронеж" />
    <meta name="description" content="Примеры построенных деревянных домов и бань из оцилиндрованного бревна в Воронеже" />
  <%- elsif controller_name=='pages' and @page and @page.name=='price' %>
    <meta name="keywords" content="Пиломатериал обрезная доска необрезная доска строительная доска оцилиндрованное бревно брус Воронеж" />
    <meta name="description" content="Прайс на пиломатериал: обрезная доска необрезная доска, строительная доска, оцилиндрованное бревно, брус в Воронеже" />
  <%- elsif controller_name=='pages' and @page and @page.name=='doska' %>
    <meta name="keywords" content="Пиломатериал обрезная доска необрезная доска столярная доска строительная доска Воронеж" />
    <meta name="description" content="Пиломатериал, обрезная доска, необрезная доска, строительная доска, столярная доска в Воронеже" />
  <%- else %>
    <meta name="keywords" content="Деревянные дома Воронеж срубы оцилиндрованное бревно пиломатериал строительство деревянных домов доска производство" />
    <meta name="description" content="Строительство, продажа деревянных домов, оцилиндрованное бревно, пиломатериал в Воронеже." />
  <% end %>
</head>
<body>
<div id="container">
  <div id="top_section">
    <div style="float:left;padding:15px;">
    <% if admin? %>
       <%= link_to "выйти", :logout, :style=>"color:#fff;background: none;" %>
    <% end %>
    </div>
    <div class="topmenu">
      <ul>
        <li><%= link_to "ГЛАВНАЯ", :root, :title => 'Воронеж лес: о фирме' %></li>
        <li><%= link_to "ПРОЕКТЫ", projects_path, :title => 'Деревянные дома: проекты домов из оцилиндрованного бревна' %></li>
        <li><%= link_to "НАШИ РАБОТЫ", works_path, :title => 'Наши работы: жилые и дачные деревянные дома, бани в Воронеже' %></li>
        <li><%= link_to "СТРОИТЕЛЬСТВО", construction_path, :title => 'Деревянные дома: подробно о стоительстве , срубы, оцилиндрованное бревно, пиломатериал' %></li>
        <li><%= link_to "ЦЕНЫ", hiperlink_path('price'), :title => 'Пиломатериал: прайс-лист на пиломатериалы, доску, оцилиндрованное бревно' %></li>
        <li><%= link_to "КОНТАКТЫ", hiperlink_path('kontact'), :style=>'background:none', :title => 'Воронеж лес: контактная информация' %></li>
      </ul>
    </div>
  </div>
  <div id="headersection">
    <span><nobr>Деревянные дома из оцилиндрованного бревна</nobr><br /></span> Имея большой опыт работы с деревом, <strong>мы выполняем полный цикл работ по строительству домов и коттеджей</strong> любых размеров и сложности: от помощи в подборе проекта (или индивидуальном проектировании) до изготовления и сборки комплекта дома и строительства «под ключ».
  </div>
  <div id="welcomesection">
    <%= yield %>
    <%- if controller_name=="pages" && @page.name=="main" %>
      <h3 style="color:#060;text-align:center;margin:20px auto;border-bottom: solid 1px;padding-bottom:10px;">Новые проекты деревянных домов из оцилиндрованного бревна</h3>
      <div style="width:760px;height:160px;margin:5px auto;">
      <%- Project.find(:all, :limit=>4, :order=>"created_at DESC").each do |proj| %>
        <%= link_to proj, :title=>"проект деревянного дома: #{proj.name}", :style=>'width:190px;display:block;float:left;text-align:center' do %>
          <strong><%= proj.name %></strong>
          <%= image_tag Image.favorite(proj.id).photo.url(:thumb), :style=>"margin:10px auto;width:150px;float:none;", :alt=>"деревянные дома в воронеже: #{proj.name}" %>
        <% end %>
      <% end %>
    </div>
    <h2 style="background:url(assets/images/header3.jpg) top left no-repeat;;text-size:16px;line-height:14px;width:180px;float:right;margin-top:0;"><a href="/projects" title="проекты деревянных домов из оцилиндрованного бревна">Все проекты</a></h2>
    <h3 style="color:#060;text-align:center;margin:60px auto 20px auto;border-bottom: solid 1px;padding-bottom:10px;clear:both;">Новые статьи: пиломатериалы, деревянные дома, оцилиндрованное бревно, строительство</h3>
    <div style="width:760px;height:160px;margin:5px auto;">
      <img src="/assets/images/building.jpg" alt="строительство деревянного дома из оцилиндрованного бревна в Воронеже зимой" style="padding-right:30px;" />
      <ul style="list-style: disc url(assets/images/disc.jpg) inside;">
      <%- Page.find(:all, :limit=>5, :order=>'created_at DESC').each do |page| %>
        <%= link_to page, :title=>"#{page.head}" do %>
          <li style="font-size: 14px;line-height:14px; padding-left: 20px;list-style: disc url(assets/images/disc.jpg) inside;"><%= page.title %></li>
        <% end %>
        <br />
      <% end %>
      </ul>
    </div>
    <h2 style="background:url(assets/images/header3.jpg) top left no-repeat;;text-size:16px;line-height:14px;width:180px;float:right;margin-top:10px;"><a href="/construction" title="пиломатериалы, доска обрезная, доска необрезная, деревянные дома, оцилиндрованное бревно ...">Все статьи</a></h2> 

    <% end %>
  </div>
  <div id="footersection"> © 2012 <a href="/kontact" title="Воронеж лес: контактная информация">Воронеж Лес</a> | Сайт разработан <a href="http://mlip.ru" title="создание и раскрутка сайтов в воронеже">ARTLevelDesign</a></div>
</div>
  <!-- Yandex.Metrika counter -->
  <div style="display:hidden">
    <script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter12874456 = new Ya.Metrika({id:12874456, enableAll: true, webvisor:true}); } catch(e) {} }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f); } else { f(); } })(document, window, "yandex_metrika_callbacks");
    </script>
  </div>
  <noscript>
    <div>
      <img src="//mc.yandex.ru/watch/12874456" style="position:absolute; left:-9999px;" alt="" />
    </div>
  </noscript>
  <!-- /Yandex.Metrika counter -->
</body>
</html>